/* Mission-first home. Uses the same routine records and parent approval rules. */
(() => {
  const R=Routine,$=id=>document.getElementById(id),today=()=>R.dateKey(new Date());
  let selected=today(),choice=null;
  const dayNames=['SEG','TER','QUA','QUI','SEX','SÁB','DOM'];
  const titles={'granola-clean':'Território limpo','teeth':'Sorriso protegido','granola-food':'Guardião da Granola','homework':'Mente em ação','schoolbag':'Pronto para a aventura','bed':'Base organizada'};
  function steps(t){return t.count===3?['Manhã','Tarde','Noite']:t.count===2?['1ª vez','2ª vez']:Array.from({length:t.count},(_,i)=>t.count===1?'Missão do dia':`${i+1}ª vez`)}
  function dayScore(w,d){const ts=w.tasks.filter(t=>t.days.includes(R.days(w.start).indexOf(d)));let total=0,done=0;ts.forEach(t=>{total+=t.count;for(let i=0;i<t.count;i++)if(w.marks[R.key(d,t.id,i)])done++});return {tasks:ts,total,done}}
  function marks(w,t){return steps(t).map((name,n)=>{const done=!!w.marks[R.key(selected,t.id,n)];return `<button type="button" class="quest-step ${done?'complete':''}" data-mark="${t.id}" data-day="${selected}" data-slot="${n}" data-mode="child" aria-pressed="${done}" aria-label="${esc(t.name)}: ${name}${done?', concluída, toque para desfazer':''}" ${w.paid?'disabled':''}><span>${done?'✓':n+1}</span>${name}</button>`}).join('')}
  const conquest=document.createElement('dialog');conquest.id='conquestDialog';conquest.setAttribute('aria-labelledby','conquestTitle');conquest.innerHTML='<div class="modal conquest-modal"><button type="button" class="close" aria-label="Fechar">×</button><p class="modal-kicker">A GRANDE RECOMPENSA</p><h2 id="conquestTitle">Minha conquista</h2><div id="conquestContents"></div><button type="button" class="secondary big" id="openTrophies">Ver meus troféus</button></div>';document.body.append(conquest);
  conquest.querySelector('.close').onclick=()=>conquest.close();
  ['.goal-card','.pots-grid','.action-grid','.info-grid','.projection-card'].forEach(s=>$('conquestContents').append(document.querySelector(s)));
  function openConquest(){conquest.showModal()}
  $('navProgress').addEventListener('click',e=>{e.stopImmediatePropagation();openConquest()},true);
  $('navProgress').querySelector('small').textContent='Conquista';
  $('openTrophies').onclick=()=>{achievementList.innerHTML=milestones.map(m=>`<div class="achievement ${state.pots.ps5>=m.v?'':'locked'}"><div class="achievement-emoji">${m.emoji}</div><div><b>Nível ${m.level} — ${esc(m.name)}</b><span>${money(m.v)}</span></div></div>`).join('');progressDialog.showModal()};
  document.querySelector('.hero h1').innerHTML='Seu poder está<br><em>em cada atitude.</em>';
  document.querySelector('.hero-description').textContent='Escolha um desafio. Faça acontecer.';
  document.querySelector('.hero-stamp').textContent='BENTINHO • DIÁRIO DE MISSÕES';
  document.querySelector('.missions-card .section-head').hidden=true;
  $('openMissions').querySelector('b').textContent='Abrir agenda completa';
  document.querySelector('.app-shell').classList.add('game-home');
  renderMissionPreview=function(){
    const w=R.week(state,R.monday(today()));if(R.monday(selected)!==w.start){selected=today();choice=null}
    const s=dayScore(w,selected),weekly=R.totals(w),pending=s.tasks.filter(t=>steps(t).some((_,n)=>!w.marks[R.key(selected,t.id,n)]));
    const task=pending.find(t=>t.id===choice)||pending[0];
    const slot=task?steps(task).findIndex((_,n)=>!w.marks[R.key(selected,task.id,n)]):-1;
    missionCount.textContent=`${s.done}/${s.total}`;
    missionPreview.innerHTML=`<section class="daily-quest ${!task?'day-complete':''}" aria-labelledby="questTitle"><div class="quest-copy"><p class="quest-eyebrow">${selected===today()?'SUA MISSÃO DE AGORA':`MISSÕES DE ${R.parse(selected).toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'})}`}</p><h2 id="questTitle">${task?esc(titles[task.id]||task.name):s.total?'Dia conquistado!':'Dia de recarregar'}</h2><p>${task?esc(task.name):s.total?'Todas as etapas deste dia foram concluídas. Bom trabalho!':'Não há tarefas programadas para este dia.'}</p>${task?`<button type="button" id="questDone" class="quest-cta" data-mark="${task.id}" data-day="${selected}" data-slot="${slot}" data-mode="child" ${w.paid?'disabled':''}>${w.paid?'Semana encerrada':'Fiz!'} <span>✓</span></button><small>${steps(task)[slot]} · escolha outra missão abaixo quando quiser</small>`:'<span class="day-medal" aria-label="Conquista do dia">✦</span>'}</div><div class="day-orbit" style="--day-progress:${s.total?s.done/s.total*360:0}deg"><div><b>${s.done}<small> / ${s.total}</small></b><span>ETAPAS DO DIA</span></div></div></section>
    <section class="week-journey" aria-labelledby="journeyTitle"><div class="quest-section-head"><div><p class="quest-eyebrow">SETE DIAS. UMA JORNADA.</p><h3 id="journeyTitle">Sua teia da semana</h3></div><span class="week-prize">${money(w.reward)}<small>recompensa semanal</small></span></div><div class="web-path">${R.days(w.start).map((d,i)=>{const ds=dayScore(w,d),full=ds.total>0&&ds.done===ds.total;return `<button type="button" data-quest-day="${d}" aria-pressed="${d===selected}" aria-label="${dayNames[i]}, ${ds.done} de ${ds.total} etapas" class="${d===selected?'selected':''} ${full?'finished':''}" ${d>today()?'disabled':''}><span>${full?'✓':i+1}</span><b>${dayNames[i]}</b><small>${d===today()?'HOJE':`${ds.done}/${ds.total}`}</small></button>`}).join('')}</div><p class="journey-status">${w.paid?'Recompensa recebida!':weekly.done>=weekly.needed?'Meta alcançada! Aguardando o fechamento e a aprovação do pai.':`Faltam <b>${Math.max(0,weekly.needed-weekly.done)} etapas</b> para chegar aos ${w.threshold}%.`} <small>${weekly.done}/${weekly.total} na semana · extras ficam separados</small></p></section>
    <section class="quest-roster" aria-labelledby="rosterTitle"><div class="quest-section-head"><h3 id="rosterTitle">Escolha seu desafio</h3><span>${s.done} de ${s.total} etapas</span></div><p class="quest-help">Marque o que fez. Toque de novo para desfazer.</p><div class="quest-grid">${s.tasks.map((t,i)=>{const n=steps(t).filter((_,j)=>w.marks[R.key(selected,t.id,j)]).length;return `<article class="quest-tile ${n===t.count?'cleared':''}"><div class="quest-tile-head"><span class="quest-number">${String(i+1).padStart(2,'0')}</span><span>${n===t.count?'CONCLUÍDA':`${n}/${t.count} ETAPAS`}</span></div><button type="button" class="pick-quest" data-pick-quest="${t.id}"><b>${esc(titles[t.id]||t.name)}</b><small>${esc(t.name)}</small></button><div class="quest-steps">${marks(w,t)}</div></article>`}).join('')}</div></section>
    <section class="special-quests"><p class="quest-eyebrow">VÁ ALÉM</p><h3>Desafios especiais</h3>${state.routine.extras.filter(x=>x.active).map(x=>`<article class="special-quest"><span class="special-star">✦</span><div><b>${esc(x.name)}</b><small>${money(x.value)} por realização · aprovação do pai</small></div><button type="button" data-extra-done="${x.id}">Fiz uma vez +</button></article>`).join('')||'<p class="quest-help">Seu pai pode liberar novos desafios aqui.</p>'}${state.routine.extraEntries.filter(x=>x.day>=w.start).map(x=>`<div class="special-status"><span>${esc(x.name)} · ${money(x.value)}</span><b>${({pending:'Aguardando aprovação',approved:'Recompensa recebida',rejected:'Não aprovado'})[x.status]}</b>${x.status==='pending'?`<button type="button" data-cancel-extra="${x.id}">Desfazer</button>`:''}</div>`).join('')}</section>
    <button type="button" class="final-reward" id="gameConquest"><span>${symbol('target')}</span><div><small>SUA GRANDE CONQUISTA</small><b>O PS5 está no caminho</b><progress value="${state.pots.ps5}" max="${state.goal}" aria-label="Progresso até o PS5"></progress></div><strong>${Math.min(100,state.pots.ps5/state.goal*100).toFixed(1).replace('.',',')}% <span>→</span></strong></button>`;
    $('gameConquest').onclick=openConquest;
  };
  document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.questDay){selected=b.dataset.questDay;choice=null;renderMissionPreview();document.querySelector(`[data-quest-day="${selected}"]`)?.focus()}if(b.dataset.pickQuest){choice=b.dataset.pickQuest;renderMissionPreview();$('questDone')?.focus();document.querySelector('.daily-quest').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'center'})}});
  // Capture pre-click state; the existing routine listener owns the mutation and persistence.
  const feedback=new WeakMap();
  document.addEventListener('click',e=>{const b=e.target.closest('[data-mark]');if(!b||b.dataset.mode==='parent'||!b.closest('#missionPreview'))return;const w=R.week(state,R.monday(today()));feedback.set(e,{w,before:dayScore(w,selected).done,id:b.dataset.mark,n:b.dataset.slot,featured:b.id==='questDone'})},true);
  document.addEventListener('click',e=>{const action=feedback.get(e);if(!action)return;const {w,before,id,n,featured}=action,after=dayScore(w,selected);if(after.done>before){toast(after.done===after.total?'Dia conquistado! Todas as missões concluídas.':'Etapa concluída. Mais um passo!');const panel=document.querySelector('.daily-quest');panel.classList.remove('quest-pop');void panel.offsetWidth;panel.classList.add('quest-pop')}const target=featured?$('questDone'):document.querySelector(`.quest-step[data-mark="${CSS.escape(id)}"][data-slot="${n}"]`);if(target)target.focus({preventScroll:true});else{const heading=$('questTitle');heading.setAttribute('tabindex','-1');heading.focus({preventScroll:true})}});
  renderAll();
})();
