/* Daily routine UI; weekly snapshots preserve past goals and payments. */
(() => {
  const R=Routine, $=id=>document.getElementById(id), today=()=>R.dateKey(new Date()), names=['Seg','Ter','Qua','Qui','Sex','Sáb','Dom'];
  const label=d=>R.parse(d).toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'});
  const uid=()=>crypto.randomUUID();
  const backup=localStorage.getItem('missaoPs5V2');
  if(!state.routine&&backup&&!localStorage.getItem('missaoPs5AntesDaAgenda'))localStorage.setItem('missaoPs5AntesDaAgenda',backup);
  R.init(state,today());
  let selected=today(),review=R.monday(today()),parentUnlocked=false,tab='week';
  const incomeButton=$('openIncome');
  incomeButton.remove(); // Move the existing form launcher into the PIN-protected money tab.
  incomeButton.className='cta big';incomeButton.type='button';incomeButton.textContent='Registrar dinheiro recebido';
  incomeButton.addEventListener('click',e=>{if(!parentUnlocked||!parentDialog.open){e.stopImmediatePropagation();return}incomeFeedback.textContent='';splitPs5.value='70';splitSpend.value='20';splitFuture.value='10'},true);
  incomeValue.min='.01';incomeValue.step='.01';
  updateSplitPreview=function(){try{const parts=MissionMoney.split(Number(incomeValue.value),[Number(splitPs5.value),Number(splitSpend.value),Number(splitFuture.value)]);splitPreview.textContent=`PS5 ${money(parts.ps5)} · Usar ${money(parts.spend)} · Futuro ${money(parts.future)}`}catch{splitPreview.textContent='Informe o valor e distribua 100% entre os potes.'}};
  saveIncome.addEventListener('click',e=>{e.stopImmediatePropagation();if(!parentUnlocked||!parentDialog.open){incomeDialog.close();return}try{const value=Number(incomeValue.value),split=[Number(splitPs5.value),Number(splitSpend.value),Number(splitFuture.value)],amounts=MissionMoney.split(value,split);for(const pot of ['ps5','spend','future'])state.pots[pot]=Math.round((state.pots[pot]+amounts[pot])*100)/100;state.history.push({type:'income',source:incomeSource.value,value:Math.round(value*100)/100,split:{ps5:split[0],spend:split[1],future:split[2]},amounts,date:new Date().toISOString(),approvedBy:'parent'});incomeValue.value='';incomeDialog.close();persist();renderMoney();toast('Dinheiro recebido e registrado pelo pai.')}catch(error){incomeFeedback.textContent=error.message}},true);
  // Child purchase flow remains a simulation; balance corrections belong to the parent.
  simulateBuy.addEventListener('click',()=>{const use=$('useMission');if(use){use.textContent='Conversar com meu pai';use.addEventListener('click',e=>{e.stopImmediatePropagation();buyDialog.close();toast('Converse com seu pai antes de usar o dinheiro da missão.')},true)}});
  const current=()=>R.week(state,R.monday(today()));
  const persist=()=>{saveState();if(missionsDialog.open)renderMissionDialog()};
  const percent=s=>`${s.percent.toFixed(1).replace('.',',')}%`;
  function slots(w,date,task,mode){const locked=w.paid||date>today();return `<div class="routine-slots">${Array.from({length:task.count},(_,n)=>{const on=!!w.marks[R.key(date,task.id,n)];return `<button type="button" data-mark="${task.id}" data-day="${date}" data-slot="${n}" data-mode="${mode}" aria-pressed="${on}" aria-label="${esc(task.name)}, ${label(date)}, ${n+1}ª vez" ${locked?'disabled':''} class="${on?'done':''}">${on?'✓':n+1}<small>${on?'Feito':'Marcar'}</small></button>`}).join('')}</div>`}
  function dayTasks(w,date,mode){const i=R.days(w.start).indexOf(date),tasks=w.tasks.filter(t=>t.days.includes(i));return tasks.map(t=>`<article class="routine-task"><div><b>${esc(t.name)}</b><small>${t.count} ${t.count===1?'vez':'vezes'} neste dia</small></div>${slots(w,date,t,mode)}</article>`).join('')||'<p class="muted">Sem tarefas programadas neste dia.</p>'}
  function score(w){const s=R.totals(w);return `<div class="week-score"><strong>${percent(s)}</strong><div>${s.done} de ${s.total} realizações na semana<small>Meta: ${w.threshold}% · ${s.needed} realizações · ${money(w.reward)}</small></div></div><progress max="${s.total||1}" value="${s.done}" aria-label="Progresso semanal"></progress><p class="routine-note">${w.paid?'Recompensa já recebida. Semana protegida.':s.done>=s.needed?'Meta alcançada! Seu pai confere e aprova no fechamento.':`Mais ${Math.max(0,s.needed-s.done)} realizações para alcançar a meta.`}</p>`}
  renderMissionPreview=function(){const w=current();const day=today();missionCount.textContent=percent(R.totals(w));missionPreview.innerHTML=score(w)+dayTasks(w,day,'child');};
  renderMissionDialog=function(){const w=current();if(R.monday(selected)!==w.start)selected=today();missionList.innerHTML=`<div class="routine-days">${R.days(w.start).map((d,i)=>`<button type="button" data-select-day="${d}" class="${selected===d?'chosen':''}" ${d>today()?'disabled':''}>${names[i]}<small>${label(d)}</small></button>`).join('')}</div><p class="routine-note">${selected===today()?'Hoje':label(selected)} · toque para marcar; toque de novo para desfazer.</p>${dayTasks(w,selected,'child')}${score(w)}${childExtras()}`;claimWeek.hidden=true;claimWeek.disabled=true;missionFeedback.textContent='O pagamento da semana é aprovado pelo pai.';};
  claimWeek.addEventListener('click',e=>{e.stopImmediatePropagation();e.preventDefault()},true);
  missionsDialog.querySelector('h2').textContent='Missões de cada dia';
  missionsDialog.querySelector('.muted').textContent='Uma marcação para cada vez que você fizer. As extras ficam separadas.';
  document.querySelector('.missions-card h2').textContent='O que já fiz hoje?';
  document.querySelector('.missions-card .mini-eyebrow').textContent='MINHA ROTINA / HOJE';
  $('openMissions').querySelector('b').textContent='Ver dias da semana e extras';
  function childExtras(){const active=state.routine.extras.filter(x=>x.active);return `<h3>Missões extras</h3><p class="routine-note">Cada realização vale um extra, depois da aprovação do pai.</p>${active.map(x=>`<article class="routine-task"><div><b>${esc(x.name)}</b><small>${money(x.value)} por realização</small></div><button type="button" class="secondary" data-extra-done="${x.id}">Fiz uma vez</button></article>`).join('')||'<p class="muted">Seu pai pode cadastrar uma missão extra.</p>'}<div>${state.routine.extraEntries.filter(x=>x.day>=R.monday(today())).map(x=>`<p class="extra-entry">${esc(x.name)} · ${label(x.day)} · ${money(x.value)} <b>${({pending:'Aguardando pai',approved:'Pago',rejected:'Não aprovado'})[x.status]}</b>${x.status==='pending'?` <button type="button" data-cancel-extra="${x.id}">Desfazer</button>`:''}</p>`).join('')}</div>`}
  document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;
    if(b.dataset.selectDay){selected=b.dataset.selectDay;renderMissionDialog()}
    if(b.dataset.mark){const isParent=b.dataset.mode==='parent';if(isParent&&!parentUnlocked)return;const w=isParent?R.week(state,review):current();if(R.mark(w,b.dataset.day,b.dataset.mark,Number(b.dataset.slot),today())){persist();if(isParent)renderReview();}}
    if(b.dataset.extraDone){const x=state.routine.extras.find(x=>x.id===b.dataset.extraDone&&x.active);if(!x)return;state.routine.extraEntries.push({id:uid(),extraId:x.id,name:x.name,value:x.value,day:today(),status:'pending'});persist();toast('Realização enviada para o pai!')}
    if(b.dataset.cancelExtra){const x=state.routine.extraEntries.find(x=>x.id===b.dataset.cancelExtra);if(x?.status==='pending'){state.routine.extraEntries=state.routine.extraEntries.filter(y=>y!==x);persist()}}
  });
  parentDialog.addEventListener('close',()=>{parentUnlocked=false;if(incomeDialog.open)incomeDialog.close()});
  addBonus.addEventListener('click',e=>{e.stopImmediatePropagation();if(!parentUnlocked)return;const value=Number(parentBonus.value);if(!Number.isFinite(value)||value<.01||value>100000){$('routineParentFeedback').textContent='Informe um bônus entre R$ 0,01 e R$ 100.000.';return}const v=Math.round(value*100)/100;state.pots.ps5=Math.round((state.pots.ps5+v)*100)/100;state.history.push({type:'parent_bonus',source:$('bonusReason').value.trim()||'Bônus do investidor',value:v,date:new Date().toISOString()});parentBonus.value='';$('bonusReason').value='';persist();toast(`Bônus de ${money(v)} registrado!`)},true);
  saveParent.addEventListener('click',e=>{e.stopImmediatePropagation();if(!parentUnlocked)return;const goal=Number(parentGoal.value),reward=Number(parentWeekly.value);if(!Number.isFinite(goal)||goal<500||!Number.isFinite(reward)||reward<=0||reward>100000){$('routineParentFeedback').textContent='Informe meta a partir de R$ 500 e recompensa positiva.';return}state.goal=goal;state.weekly=Math.round(reward*100)/100;const effective=R.add(R.monday(today()),7),p=structuredClone([...state.routine.plans].filter(x=>x.effective<=effective).sort((a,b)=>b.effective.localeCompare(a.effective))[0]);p.effective=effective;p.reward=state.weekly;state.routine.plans=state.routine.plans.filter(x=>x.effective!==effective);state.routine.plans.push(p);persist();$('routineParentFeedback').textContent=`Ajustes salvos. Recompensa semanal válida a partir de ${label(effective)}.`;},true);
  navParent.addEventListener('click',()=>{parentUnlocked=false});
  // Called by the existing PIN handler only after a correct PIN.
  ensureParentTools=function(){parentUnlocked=true;if(!$('routineParent'))buildParent();tab='week';review=R.monday(today());showTab();};
  function buildParent(){
    const settings=document.createElement('section');settings.id='routineSettings';while(parentPanel.firstChild)settings.append(parentPanel.firstChild);parentPanel.append(settings);
    settings.insertAdjacentHTML('beforeend','<label>Motivo do bônus<input id="bonusReason" maxlength="100" placeholder="Ex.: Capricho com a Granola"></label><p class="routine-note">O bônus vai para a Missão PS5. O valor semanal acima será usado nos próximos planos; a semana em andamento mantém seu valor.</p><p class="routine-note">Confira o indicador de conexão no início do app. Só “salvo online” confirma o envio para os outros aparelhos da família. Sem conexão familiar configurada, os dados ficam apenas neste navegador.</p><button type="button" class="secondary big" id="routineBackup">Baixar cópia dos dados</button>');
    parentPanel.insertAdjacentHTML('afterbegin',`<div id="routineParent"><div class="routine-tabs">${[['week','Semana'],['plan','Rotina'],['extras','Extras'],['settings','Ajustes'],['history','Histórico']].map(([id,title])=>`<button type="button" data-routine-tab="${id}">${title}</button>`).join('')}</div><section id="routineWeek"></section><section id="routinePlan" hidden></section><section id="routineExtras" hidden></section><section id="routineHistory" hidden></section><p id="routineParentFeedback" role="status"></p></div>`);
    document.querySelector('.routine-tabs').insertAdjacentHTML('beforeend','<button type="button" data-routine-tab="money">Dinheiro</button>');
    $('routineParent').insertAdjacentHTML('beforeend','<section id="routineMoney" hidden></section>');
    $('routineParent').addEventListener('click',e=>{const b=e.target.closest('button');if(!parentUnlocked||!b)return;if(b.dataset.routineTab){tab=b.dataset.routineTab;showTab()}});
    $('routineBackup').onclick=()=>{if(!parentUnlocked)return;const url=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`missao-ps5-${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
    addBonus.addEventListener('click',()=>{if(!parentUnlocked)return;const last=state.history.at(-1);if(last?.type==='parent_bonus'){last.source=$('bonusReason').value.trim()||'Bônus do investidor';$('bonusReason').value='';persist()}});
  }
  function showTab(){if(!parentUnlocked)return;for(const [id,t] of [['routineWeek','week'],['routinePlan','plan'],['routineExtras','extras'],['routineSettings','settings'],['routineHistory','history'],['routineMoney','money']])$(id).hidden=tab!==t;document.querySelectorAll('[data-routine-tab]').forEach(b=>b.classList.toggle('chosen',b.dataset.routineTab===tab));$('routineParentFeedback').textContent='';if(tab==='week')renderReview();if(tab==='plan')renderPlan();if(tab==='extras')renderExtras();if(tab==='history')renderRoutineHistory();if(tab==='money')renderMoney()}
  function renderReview(){const w=R.week(state,review),s=R.totals(w);$('routineWeek').innerHTML=`<h2>Fechamento semanal</h2><div class="review-nav"><button type="button" id="previousWeek" ${review<=R.monday(state.routine.started)?'disabled':''}>← Anterior</button><b>${label(review)} a ${label(R.add(review,6))}</b><button type="button" id="nextWeek" ${review>=R.monday(today())?'disabled':''}>Próxima →</button></div>${score(w)}<div class="routine-totals">${s.rows.map(r=>`<p><span>${esc(r.task.name)}</span><b>${r.done}/${r.total}</b></p>`).join('')}</div><p class="routine-note">Todas as realizações têm o mesmo peso. Extras não entram na meta. A meta considera a semana inteira, de segunda a domingo.</p><button type="button" class="cta big" id="approveRoutineWeek" ${w.paid||s.done<s.needed||!s.total||today()<R.add(review,6)?'disabled':''}>${w.paid?'Semana já paga':`Aprovar e pagar ${money(w.reward)}`}</button><p class="routine-note">${today()<R.add(review,6)?'Pagamento disponível a partir de domingo.':''}</p><h3>Conferir e corrigir marcações</h3>${R.days(review).map((d,i)=>`<details><summary>${names[i]} · ${label(d)}${d>today()?' · ainda não chegou':''}</summary>${dayTasks(w,d,'parent')}</details>`).join('')}`;
    $('previousWeek').onclick=()=>{review=R.add(review,-7);renderReview()};$('nextWeek').onclick=()=>{review=R.add(review,7);renderReview()};$('approveRoutineWeek').onclick=()=>{if(!parentUnlocked)return;const error=R.approve(state,w,today());if(error){$('routineParentFeedback').textContent=error;return}persist();renderReview();toast('Semana aprovada e recompensa registrada!')};
  }
  function taskEditor(t){return `<fieldset class="routine-editor" data-task-id="${t.id}"><label>Nome da tarefa<input class="task-name" value="${esc(t.name)}" maxlength="100"></label><label>Vezes por dia<input class="task-count" type="number" min="1" max="10" value="${t.count}"></label><div class="routine-days-editor">${names.map((n,i)=>`<label><input type="checkbox" value="${i}" ${t.days.includes(i)?'checked':''}>${n}</label>`).join('')}</div><button type="button" class="text-remove">Retirar do próximo plano</button></fieldset>`}
  function renderPlan(){const next=R.add(R.monday(today()),7),p=[...state.routine.plans].filter(p=>p.effective<=next).sort((a,b)=>b.effective.localeCompare(a.effective))[0],w=current(),empty=!Object.values(w.marks).some(Boolean)&&!w.paid; $('routinePlan').innerHTML=`<h2>Editar a rotina</h2><p class="routine-note">Alterações valem a partir de ${label(next)}. As semanas anteriores guardam suas tarefas, metas e valores.</p><label>Meta para ganhar (%)<input id="routineThreshold" type="number" min="1" max="100" value="${p.threshold}"></label><label>Valor semanal (R$)<input id="routineReward" type="number" min="0.01" max="100000" step="0.01" value="${p.reward}"></label>${empty?'<label class="apply-now"><input id="applyRoutineNow" type="checkbox"> Começar já nesta semana (ainda não há marcações)</label>':''}<div id="routineTaskEditor">${p.tasks.map(taskEditor).join('')}</div><button type="button" class="secondary big" id="addRoutineTask">+ Adicionar tarefa</button><button type="button" class="cta big" id="saveRoutinePlan">Salvar rotina</button>`;
    $('routineTaskEditor').onclick=e=>{if(e.target.matches('.text-remove'))e.target.closest('fieldset').remove()};$('addRoutineTask').onclick=()=>{$('routineTaskEditor').insertAdjacentHTML('beforeend',taskEditor({id:uid(),name:'',count:1,days:[0,1,2,3,4,5,6]}))};
    $('saveRoutinePlan').onclick=()=>{if(!parentUnlocked)return;const tasks=[...document.querySelectorAll('#routineTaskEditor fieldset')].map(el=>({id:el.dataset.taskId,name:el.querySelector('.task-name').value.trim(),count:Number(el.querySelector('.task-count').value),days:[...el.querySelectorAll('input[type=checkbox]:checked')].map(c=>Number(c.value))}));const threshold=Number($('routineThreshold').value),reward=Number($('routineReward').value);if(!tasks.length||tasks.some(t=>!t.name||!Number.isInteger(t.count)||t.count<1||t.count>10||!t.days.length)||!Number.isFinite(threshold)||threshold<1||threshold>100||!Number.isFinite(reward)||reward<=0||reward>100000){$('routineParentFeedback').textContent='Preencha nomes, 1 a 10 vezes ao dia, ao menos um dia, meta de 1 a 100% e valor positivo.';return}const now=$('applyRoutineNow')?.checked&&empty,effective=now?w.start:next;state.routine.plans=state.routine.plans.filter(p=>p.effective!==effective);state.routine.plans.push({effective,tasks,threshold,reward:Math.round(reward*100)/100});if(now){delete state.routine.weeks[w.start];R.week(state,w.start)}state.weekly=reward;parentWeekly.value=reward;persist();$('routineParentFeedback').textContent=`Rotina salva. Começa em ${label(effective)}.`;};
  }
  function renderExtras(){const pending=state.routine.extraEntries.filter(x=>x.status==='pending');$('routineExtras').innerHTML=`<h2>Extras por realização</h2><p class="routine-note">Ele marca “Fiz uma vez”. Você confere e aprova o valor para a Missão PS5, separadamente dos 80%.</p><label>Nome<input id="extraName" maxlength="100" placeholder="Ex.: Lavar a bicicleta"></label><label>Valor por realização (R$)<input id="extraValue" type="number" min="0.01" step="0.01" placeholder="5"></label><button type="button" id="createExtra" class="secondary big">Cadastrar extra</button><div>${state.routine.extras.map(x=>`<p class="extra-entry"><b>${esc(x.name)}</b> · ${money(x.value)} <button type="button" data-toggle-extra="${x.id}">${x.active?'Pausar':'Ativar'}</button></p>`).join('')}</div><h3>Realizações para conferir (${pending.length})</h3>${pending.map(x=>`<article class="extra-approval"><b>${esc(x.name)}</b><p>${label(x.day)} · ${money(x.value)}</p><button type="button" data-approve-extra="${x.id}">Aprovar e pagar</button><button type="button" data-reject-extra="${x.id}">Não aprovar</button></article>`).join('')||'<p class="muted">Nenhuma realização pendente.</p>'}`;
    $('createExtra').onclick=()=>{if(!parentUnlocked)return;const name=$('extraName').value.trim(),value=Number($('extraValue').value);if(!name||!Number.isFinite(value)||value<.01||value>100000){$('routineParentFeedback').textContent='Informe nome e valor válido.';return}state.routine.extras.push({id:uid(),name,value:Math.round(value*100)/100,active:true});persist();renderExtras()};
    $('routineExtras').onclick=e=>{if(!parentUnlocked)return;const b=e.target.closest('button');if(!b)return;if(b.dataset.toggleExtra){const x=state.routine.extras.find(x=>x.id===b.dataset.toggleExtra);x.active=!x.active;persist();renderExtras()}const id=b.dataset.approveExtra||b.dataset.rejectExtra;if(id){const x=state.routine.extraEntries.find(x=>x.id===id);if(!x||x.status!=='pending')return;x.status=b.dataset.approveExtra?'approved':'rejected';if(x.status==='approved'){state.pots.ps5=Math.round((state.pots.ps5+x.value)*100)/100;state.history.push({type:'extra',source:x.name,value:x.value,entryId:x.id,date:new Date().toISOString()})}persist();renderExtras()}};
  }
  function renderMoney(){
    if(!parentUnlocked||!$('routineMoney'))return;
    const pots=[['ps5','Missão PS5'],['spend','Dinheiro livre'],['future','Futuro']];
    $('routineMoney').innerHTML=`<h2>Dinheiro da missão</h2><div class="routine-totals">${pots.map(([id,name])=>`<p><span>${name}</span><b>${money(state.pots[id])}</b></p>`).join('')}<p><span>Total guardado</span><b>${money(pots.reduce((sum,[id])=>sum+state.pots[id],0))}</b></p></div><p class="routine-note">Presente, mesada ou dinheiro recebido por fora: registre o valor e escolha como dividir. Só o pai pode adicionar dinheiro.</p><div id="parentIncomeLauncher"></div><details><summary>Corrigir o saldo dos potes</summary><p class="routine-note">Informe o valor final correto de cada pote. Isso substitui os saldos abaixo; não é uma entrada de dinheiro. Use também para registrar uma saída combinada com seu filho.</p>${pots.map(([id,name])=>`<label>${name} — saldo correto (R$)<input id="correct-${id}" type="number" min="0" max="1000000" step="0.01" inputmode="decimal" value="${state.pots[id].toFixed(2)}"></label>`).join('')}<label>Motivo da correção<input id="balanceReason" maxlength="120" placeholder="Ex.: Conferência do dinheiro em caixa"></label><div id="correctionPreview" class="routine-note" aria-live="polite"></div><button type="button" id="confirmBalances" class="secondary big">Confirmar correção dos saldos</button><p id="balanceFeedback" role="status" class="routine-note"></p></details><p class="routine-note">Etapas cumpridas não alteram o saldo sozinhas. A recompensa semanal entra quando você aprova a semana; extras e bônus são registrados separadamente.</p>`;
    $('parentIncomeLauncher').append(incomeButton);
    function values(){return Object.fromEntries(pots.map(([id])=>{const text=$(`correct-${id}`).value;return [id,text.trim()===''?NaN:Math.round(Number(text)*100)/100]}))}
    function preview(){const after=values();$('correctionPreview').textContent=pots.map(([id,name])=>`${name}: ${money(state.pots[id])} → ${Number.isFinite(after[id])&&after[id]>=0?money(after[id]):'valor inválido'}`).join(' · ')}
    pots.forEach(([id])=>$(`correct-${id}`).oninput=preview);preview();
    $('confirmBalances').onclick=()=>{if(!parentUnlocked||!parentDialog.open)return;const after=values(),reason=$('balanceReason').value.trim();if(Object.values(after).some(n=>!Number.isFinite(n)||n<0||n>1000000)||!reason){$('balanceFeedback').textContent='Preencha os três saldos (zero é permitido) e o motivo da correção.';return}const before={...state.pots};if(pots.every(([id])=>before[id]===after[id])){$('balanceFeedback').textContent='Os valores já estão corretos. Nenhuma alteração feita.';return}state.pots=after;state.history.push({type:'balance_adjustment',source:reason,before,after:{...after},value:Math.round(pots.reduce((sum,[id])=>sum+after[id]-before[id],0)*100)/100,date:new Date().toISOString(),approvedBy:'parent'});persist();renderMoney();$('routineParentFeedback').textContent='Saldos corrigidos. Valores anteriores e motivo guardados no histórico.';};
  }
  function renderRoutineHistory(){$('routineHistory').innerHTML='<h2>Histórico da missão</h2>'+[...state.history].reverse().map(x=>`<div class="history-item"><span>${x.type==='balance_adjustment'?'↔':x.type==='purchase'?'−':'+'}</span><div><b>${x.type==='balance_adjustment'?'Correção: ':''}${esc(x.source||({weekly:'Recompensa semanal',initial:'Início da missão',parent_bonus:'Bônus do investidor'})[x.type]||'Entrada de dinheiro')}</b><small>${new Date(x.date).toLocaleDateString('pt-BR')}${x.done!==undefined?` · ${x.done}/${x.total} realizações`:''}</small>${x.type==='balance_adjustment'?`<small>PS5: ${money(x.before.ps5)} → ${money(x.after.ps5)}<br>Livre: ${money(x.before.spend)} → ${money(x.after.spend)}<br>Futuro: ${money(x.before.future)} → ${money(x.after.future)}</small>`:''}</div><b>${money(x.value)}</b></div>`).join('')}
  // Persist the migration once; old tasks and history remain available in the backup and state.
  document.addEventListener('mission:cloud-updated',()=>{if(parentUnlocked&&parentDialog.open){if(tab==='week')renderReview();if(tab==='history')renderRoutineHistory();if(tab==='extras')renderExtras();if(tab==='money')renderMoney()}});
  current();localStorage.setItem('missaoPs5V2',JSON.stringify(state));renderAll();
  document.addEventListener('visibilitychange',()=>{if(!document.hidden){current();renderAll();if(missionsDialog.open)renderMissionDialog()}});
})();
