const assert=require('node:assert/strict'),{randomUUID}=require('node:crypto'),{fixture}=require('./google-fixture.cjs'),R=require('../routine-model.js');
const f=fixture(),today=f.context.today_(),state={goal:4000,weekly:10,pots:{ps5:300,spend:0,future:0},history:[],claimedWeeks:[],tasks:[],completedTasks:[],streak:0};
R.init(state,today);const week=R.week(state,today);
const commit=(data,revision,pin,op=randomUUID())=>f.call('mission_commit',{p_data:data,p_revision:revision,p_pin:pin,p_operation:op}).value;
assert.equal(f.call('mission_read',{},'wrong').auth,true);
assert.equal(f.call('mission_read').value.data,null);
assert.equal(commit(state,0).denied,true);
assert.equal(f.call('mission_check_pin',{p_pin:f.pin}).value,true);
assert.equal(commit(state,0,f.pin).ok,true);
const next=structuredClone(state),task=week.tasks.find(t=>t.days.includes((R.parse(today).getDay()+6)%7));next.routine.weeks[week.start].marks[R.key(today,task.id,0)]=true;
const op=randomUUID();assert.equal(commit(next,1,null,op).revision,2);assert.equal(commit(next,1,null,op).revision,2);
assert.equal(commit(state,1).conflict,true);
const money=structuredClone(next);money.pots.ps5=999;assert.equal(commit(money,2).denied,true);assert.equal(commit(money,2,f.pin).ok,true);
const future=structuredClone(money);future.routine.weeks[week.start].marks[R.key(R.add(today,7),task.id,0)]=true;assert.equal(commit(future,3).denied,true);
const invalid=structuredClone(money);invalid.pin='123456';assert.ok(f.call('mission_commit',{p_data:invalid,p_revision:3,p_operation:randomUUID(),p_pin:f.pin}).error);
const extra={id:randomUUID(),name:'Teste extra',value:5,active:true},withExtra=structuredClone(money);withExtra.routine.extras.push(extra);assert.equal(commit(withExtra,3,f.pin).ok,true);
const pending=structuredClone(withExtra);pending.routine.extraEntries.push({id:randomUUID(),extraId:extra.id,name:extra.name,value:extra.value,day:today,status:'pending'});assert.equal(commit(pending,4).ok,true);
const approved=structuredClone(pending);approved.routine.extraEntries[0].status='approved';assert.equal(commit(approved,5).denied,true);
assert.equal(f.book.getSheetByName('Resumo').getRange('B6').getValues()[0][0],999);
assert.equal(f.book.getSheetByName('Marcações').getRange('E5').getValues()[0][0],'Sim');
assert.equal(f.context.cell_('=IMPORTXML("x")'),"'=IMPORTXML(\"x\")");
for(let i=0;i<5;i++)assert.equal(f.call('mission_check_pin',{p_pin:'wrong'}).value,false);assert.equal(f.call('mission_check_pin',{p_pin:f.pin}).value,false);
const journal=f.book.getSheetByName('_Estado');assert.equal(journal.getLastRow(),6);journal.rows[5][4]='corrupt';assert.ok(f.call('mission_read').error);assert.equal(journal.getLastRow(),6);
console.log('PASS Google backend: private key, PIN, marks, extra approvals, money protection, CAS, idempotency, projections, PIN limits, corruption detection.');
